all:
	$(CC) example-mist-app.c ../../libmist.a -I.. -I../../wish_app -I../../wish_app_deps  -I../../deps/libuv/include -I../../deps/wish-rpc-c99/src -I../../deps/bson -I../../deps/uthash/include -luv -o example-mist-app
